apiVersion: v1
kind: Secret
metadata:
  name: user-api-secret
type: Opaque
stringData:
  USERNAME: ${API_USERNAME}
  PASSWORD: ${API_PASSWORD}
  SWAGGER_USERNAME: ${SWAGGER_USERNAME}
  SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
